"""
formatar_mindtrace.py - Convert MindTrace CSV exports to formatted XLSX files.

Converts tracking_data.csv files generated by MindTrace into Excel workbooks
with apparatus-specific formatting, colour themes, and statistical summaries.
"""

import csv
import os
import sys
import zipfile
from io import BytesIO
from typing import Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# XML helpers
# ---------------------------------------------------------------------------

def escape_xml(text: str) -> str:
    """Escape special characters so *text* is safe inside XML content."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )


def get_col_name(col_index: int) -> str:
    """Convert a zero-based column index to an Excel column letter (A, B, …, AA, …)."""
    if col_index < 26:
        return chr(65 + col_index)
    return f"{chr(64 + col_index // 26)}{chr(65 + col_index % 26)}"


# ---------------------------------------------------------------------------
# Text normalisation (accent-folding for header matching)
# ---------------------------------------------------------------------------

_ACCENT_MAP: Dict[str, str] = {
    "á": "a", "à": "a", "â": "a", "ã": "a", "ä": "a",
    "é": "e", "è": "e", "ê": "e", "ë": "e",
    "í": "i", "ì": "i", "î": "i", "ï": "i",
    "ó": "o", "ò": "o", "ô": "o", "õ": "o", "ö": "o",
    "ú": "u", "ù": "u", "û": "u", "ü": "u",
    "ç": "c", "ñ": "n",
}


def normalize_text(text: str) -> str:
    """Lowercase and fold accented characters to their ASCII equivalents."""
    normalized = str(text or "").strip().lower()
    for accented_char, plain_char in _ACCENT_MAP.items():
        normalized = normalized.replace(accented_char, plain_char)
    return normalized


def contains_any(text: str, patterns: List[str]) -> bool:
    """Return True if the normalised *text* contains any of the normalised *patterns*."""
    normalized_text = normalize_text(text)
    return any(normalize_text(pattern) in normalized_text for pattern in patterns)


def headers_have_any(headers: List[str], patterns: List[str]) -> bool:
    """Return True if at least one header in *headers* matches any pattern."""
    return any(contains_any(header, patterns) for header in headers)


# ---------------------------------------------------------------------------
# Language detection
# ---------------------------------------------------------------------------

def detect_language(headers: List[str]) -> str:
    """Infer the CSV language from column header keywords.

    Returns:
        "en" for English, "es" for Spanish, "pt" for Portuguese (default).
    """
    if headers_have_any(headers, ["video directory", "object pair", "time in center", "average speed", "duration"]):
        return "en"
    if headers_have_any(headers, ["directorio del video", "tiempo en centro", "velocidad media", "duracion", "tratamiento"]):
        return "es"
    return "pt"


# ---------------------------------------------------------------------------
# Apparatus detection
# ---------------------------------------------------------------------------

_APPARATUS_LABELS: Dict[str, Dict[str, str]] = {
    "nor":     {"pt": "Reconhecimento de Objetos (NOR)", "en": "Object Recognition (NOR)",  "es": "Reconocimiento de Objetos (NOR)"},
    "ei":      {"pt": "Esquiva Inibitoria (EI)",         "en": "Inhibitory Avoidance (EI)", "es": "Evitacion Inhibitoria (EI)"},
    "ca":      {"pt": "Campo Aberto (CA)",               "en": "Open Field (CA)",           "es": "Campo Abierto (CA)"},
    "cc":      {"pt": "Comportamento Complexo (CC)",     "en": "Complex Behavior (CC)",     "es": "Comportamiento Complejo (CC)"},
    "generic": {"pt": "Dados do Experimento",            "en": "Experiment Data",           "es": "Datos del Experimento"},
}

_APPARATUS_COLORS: Dict[str, str] = {
    "nor":     "FFAB3D4C",
    "ei":      "FFC8A000",
    "ca":      "FF3D7AAB",
    "cc":      "FF7A3DAB",
    "generic": "FFAB3D4C",
}


def detect_apparatus(headers: List[str], lang: str) -> Tuple[str, str]:
    """Determine apparatus type and its accent colour from CSV headers.

    Args:
        headers: Column header strings.
        lang: Language code ("pt", "en", "es").

    Returns:
        Tuple of (apparatus_label, colour_hex).
    """
    if headers_have_any(headers, ["Par de Objetos", "Object Pair"]):
        apparatus_key = "nor"
    elif headers_have_any(headers, ["latencia (s)", "tempo plataforma (s)", "platform time (s)", "tiempo plataforma (s)"]):
        apparatus_key = "ei"
    elif headers_have_any(headers, ["tempo no centro (s)", "time in center (s)", "tiempo en centro (s)", "visitas ao centro", "center visits", "visitas al centro"]):
        apparatus_key = "ca"
    elif headers_have_any(headers, ["duracao (min)", "duration (min)", "duracion (min)"]):
        apparatus_key = "cc"
    else:
        apparatus_key = "generic"

    return _APPARATUS_LABELS[apparatus_key][lang], _APPARATUS_COLORS[apparatus_key]


# ---------------------------------------------------------------------------
# Data grouping
# ---------------------------------------------------------------------------

def group_rows_by_column(
    rows: List[List[str]],
    headers: List[str],
    split_patterns: List[str],
    lang: str,
) -> Tuple[Dict[str, List[List[str]]], int]:
    """Split *rows* into groups keyed by the value in the first matching column.

    Args:
        rows: Data rows (without header).
        headers: Column header strings.
        split_patterns: Substrings to match against headers to pick the split column.
        lang: Language code for the default group name ("pt", "en", "es").

    Returns:
        Tuple of (groups dict, split_col_index). split_col_index is -1 when no
        matching column was found and all rows land in a single default group.
    """
    default_group = {"pt": "Geral",  "en": "General", "es": "General"}[lang]
    fallback_cell = {"pt": "Dados",  "en": "Data",    "es": "Datos"}[lang]

    split_col_index = next(
        (idx for idx, header in enumerate(headers) if contains_any(header, split_patterns)),
        -1,
    )

    groups: Dict[str, List[List[str]]] = {}
    if split_col_index >= 0:
        for row in rows:
            if len(row) > split_col_index:
                group_key = row[split_col_index] if row[split_col_index] else fallback_cell
                groups.setdefault(group_key, []).append(row)
    else:
        groups[default_group] = rows

    return groups, split_col_index


# ---------------------------------------------------------------------------
# CSV reading
# ---------------------------------------------------------------------------

def read_csv_rows(source_path: str) -> List[List[str]]:
    """Read all rows from *source_path*, trying common encodings in order.

    Args:
        source_path: Path to the CSV file.

    Returns:
        List of rows (each a list of strings). Empty list if all encodings fail
        or the file contains no data.
    """
    for encoding in ("utf-8-sig", "utf-8", "latin-1"):
        try:
            with open(source_path, "r", encoding=encoding) as csv_file:
                return list(csv.reader(csv_file))
        except UnicodeDecodeError:
            continue
    return []


# ---------------------------------------------------------------------------
# XLSX internal helpers
# ---------------------------------------------------------------------------

_EXCLUDE_NUMERIC_HEADERS = {
    "animal", "campo", "field", "dia", "day",
    "par de objetos", "object pair",
    "diretorio do video", "video directory", "directorio del video",
}


def _find_metric_columns(headers: List[str]) -> Tuple[int, int, int, int]:
    """Return (velocity_idx, distance_idx, zone1_time_idx, zone2_time_idx), -1 when absent."""
    velocity_idx = distance_idx = zone1_time_idx = zone2_time_idx = -1
    for col_index, header_name in enumerate(headers):
        if contains_any(header_name, ["velocidade media", "average speed", "velocidad media"]):
            velocity_idx = col_index
        elif contains_any(header_name, ["distancia total", "total distance"]):
            distance_idx = col_index
        elif contains_any(header_name, ["tempo no centro", "time in center", "tiempo en centro",
                                        "tempo plataforma", "platform time", "tiempo plataforma"]):
            zone1_time_idx = col_index
        elif contains_any(header_name, ["tempo na borda", "time at border", "tiempo en borde",
                                        "tempo grade", "grid time", "tiempo rejilla"]):
            zone2_time_idx = col_index
    return velocity_idx, distance_idx, zone1_time_idx, zone2_time_idx


def _recalculate_zero_velocity(
    rows: List[List[str]],
    velocity_idx: int,
    distance_idx: int,
    zone1_time_idx: int,
    zone2_time_idx: int,
) -> None:
    """Impute velocity = distance / time for rows whose stored velocity is ~0.

    Modifies *rows* in-place. No-op when any required column index is -1.
    """
    if any(idx < 0 for idx in (velocity_idx, distance_idx, zone1_time_idx, zone2_time_idx)):
        return

    for row in rows:
        try:
            velocity = float(str(row[velocity_idx]).replace(",", ".")) if len(row) > velocity_idx and row[velocity_idx] else 0.0
            if velocity >= 0.001:
                continue
            distance   = float(str(row[distance_idx]).replace(",", "."))   if len(row) > distance_idx   and row[distance_idx]   else 0.0
            zone1_time = float(str(row[zone1_time_idx]).replace(",", ".")) if len(row) > zone1_time_idx and row[zone1_time_idx] else 0.0
            zone2_time = float(str(row[zone2_time_idx]).replace(",", ".")) if len(row) > zone2_time_idx and row[zone2_time_idx] else 0.0
            total_time = zone1_time + zone2_time
            if total_time > 0.5:
                row[velocity_idx] = "{:.3f}".format(distance / total_time).replace(".", ",")
        except Exception:
            pass


def _build_styles_xml(color_hex: str) -> str:
    """Return the xl/styles.xml content for a given accent colour."""
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
    <fonts count="4">
        <font><sz val="11"/><name val="Calibri"/></font>
        <font><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/><b/></font>
        <font><sz val="18"/><color rgb="FFFFFFFF"/><name val="Segoe UI"/><b/></font>
        <font><sz val="11"/><color rgb="FF374151"/><name val="Segoe UI"/><b/></font>
    </fonts>
    <fills count="4">
        <fill><patternFill patternType="none"/></fill>
        <fill><patternFill patternType="gray125"/></fill>
        <fill><patternFill patternType="solid"><fgColor rgb="{color_hex}"/><bgColor indexed="64"/></patternFill></fill>
        <fill><patternFill patternType="solid"><fgColor rgb="FFF9FAFB"/><bgColor indexed="64"/></patternFill></fill>
    </fills>
    <borders count="2">
        <border><left/><right/><top/><bottom/><diagonal/></border>
        <border><left style="thin"><color rgb="FFE5E7EB"/></left><right style="thin"><color rgb="FFE5E7EB"/></right><top style="thin"><color rgb="FFE5E7EB"/></top><bottom style="thin"><color rgb="FFE5E7EB"/></bottom><diagonal/></border>
    </borders>
    <cellXfs count="6">
        <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"><alignment horizontal="center" vertical="center"/></xf>
        <xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1"><alignment horizontal="center" vertical="center"/></xf>
        <xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1"><alignment horizontal="center" vertical="center"/></xf>
        <xf numFmtId="0" fontId="2" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"><alignment horizontal="center" vertical="center"/></xf>
        <xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"><alignment horizontal="center" vertical="center"/></xf>
        <xf numFmtId="0" fontId="3" fillId="3" borderId="0" xfId="0" applyFont="1" applyFill="1"><alignment horizontal="center" vertical="center"/></xf>
    </cellXfs>
</styleSheet>"""


def _build_worksheet_xml(
    headers: List[str],
    rows: List[List[str]],
    base_name: str,
    apparatus_label: str,
    lang: str,
) -> bytes:
    """Render a single worksheet as OOXML bytes.

    Args:
        headers: Column header strings.
        rows: Data rows for this sheet (modified in-place for velocity imputation).
        base_name: Experiment name shown in title row.
        apparatus_label: Apparatus description shown in row 2.
        lang: Language code for stats string localisation.

    Returns:
        Raw bytes of the worksheet XML.
    """
    total_rows = len(rows)
    animal_col_idx = headers.index("Animal") if "Animal" in headers else -1
    unique_animals = (
        len(set(row[animal_col_idx] for row in rows if len(row) > animal_col_idx))
        if animal_col_idx >= 0 else 0
    )

    stats_str = {
        "en": f"Total Records in Sheet: {total_rows} | Unique Animals: {unique_animals} | Data Columns: {len(headers)}",
        "es": f"Total de Registros en la Hoja: {total_rows} | Animales Unicos: {unique_animals} | Columnas de Datos: {len(headers)}",
        "pt": f"Total de Registros na Planilha: {total_rows} | Animais Unicos: {unique_animals} | Colunas de Dados: {len(headers)}",
    }[lang]

    col_widths = [max(12, len(str(header)) + 4) for header in headers]
    for row in rows:
        for col_index, cell_value in enumerate(row):
            if col_index < len(col_widths):
                col_widths[col_index] = max(col_widths[col_index], len(str(cell_value)) + 1)

    velocity_idx, distance_idx, zone1_time_idx, zone2_time_idx = _find_metric_columns(headers)
    _recalculate_zero_velocity(rows, velocity_idx, distance_idx, zone1_time_idx, zone2_time_idx)

    buf = BytesIO()
    buf.write(b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n')
    buf.write(b'<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">\n')

    buf.write(b"  <cols>\n")
    for col_index in range(len(headers)):
        width = min(255, col_widths[col_index] * 1.1)
        buf.write(f'    <col min="{col_index+1}" max="{col_index+1}" width="{width:.2f}" customWidth="1"/>\n'.encode("utf-8"))
    buf.write(b"  </cols>\n")
    buf.write(b"  <sheetData>\n")

    buf.write(b'    <row r="1" ht="30" customHeight="1">\n')
    buf.write(f'      <c r="A1" s="3" t="inlineStr"><is><t>{escape_xml(base_name)}</t></is></c>\n'.encode("utf-8"))
    buf.write(b"    </row>\n")

    buf.write(b'    <row r="2" ht="20" customHeight="1">\n')
    buf.write(f'      <c r="A2" s="4" t="inlineStr"><is><t>{escape_xml(apparatus_label)}</t></is></c>\n'.encode("utf-8"))
    buf.write(b"    </row>\n")

    buf.write(b'    <row r="3" ht="20" customHeight="1">\n')
    buf.write(f'      <c r="A3" s="5" t="inlineStr"><is><t>{escape_xml(stats_str)}</t></is></c>\n'.encode("utf-8"))
    buf.write(b"    </row>\n")

    buf.write(b'    <row r="4" ht="20" customHeight="1">\n')
    for col_index, header in enumerate(headers):
        cell_ref = f"{get_col_name(col_index)}4"
        buf.write(f'      <c r="{cell_ref}" s="1" t="inlineStr"><is><t>{escape_xml(header)}</t></is></c>\n'.encode("utf-8"))
    buf.write(b"    </row>\n")

    for row_index, row in enumerate(rows, 5):
        buf.write(f'    <row r="{row_index}">\n'.encode("utf-8"))
        for col_index, cell_value in enumerate(row):
            cell_ref = f"{get_col_name(col_index)}{row_index}"
            header_normalized = normalize_text(headers[col_index] if col_index < len(headers) else "")
            val_str = str(cell_value).strip()

            is_numeric = False
            if header_normalized not in _EXCLUDE_NUMERIC_HEADERS:
                try:
                    numeric_val = float(val_str.replace(",", "."))
                    val_str = str(numeric_val)
                    is_numeric = True
                except ValueError:
                    pass

            if is_numeric:
                buf.write(f'      <c r="{cell_ref}" s="2"><v>{val_str}</v></c>\n'.encode("utf-8"))
            else:
                buf.write(f'      <c r="{cell_ref}" s="2" t="inlineStr"><is><t>{escape_xml(val_str)}</t></is></c>\n'.encode("utf-8"))
        buf.write(b"    </row>\n")

    buf.write(b"  </sheetData>\n")
    last_col = get_col_name(len(headers) - 1) if headers else "A"
    buf.write(b'  <mergeCells count="3">')
    buf.write(f'<mergeCell ref="A1:{last_col}1"/>'.encode("utf-8"))
    buf.write(f'<mergeCell ref="A2:{last_col}2"/>'.encode("utf-8"))
    buf.write(f'<mergeCell ref="A3:{last_col}3"/>'.encode("utf-8"))
    buf.write(b"</mergeCells>\n")
    buf.write(b"</worksheet>")
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Public XLSX writer
# ---------------------------------------------------------------------------

def create_xlsx(
    dest_path: str,
    base_name: str,
    apparatus_label: str,
    headers: List[str],
    groups: Dict[str, List[List[str]]],
    color_hex: str = "FFAB3D4C",
    lang: str = "pt",
) -> None:
    """Write an OOXML .xlsx file to *dest_path*.

    Args:
        dest_path: Output file path.
        base_name: Experiment name shown in the title row of each sheet.
        apparatus_label: Apparatus description shown in row 2.
        headers: Column header strings.
        groups: Mapping of sheet-name to list of data rows.
        color_hex: ARGB accent colour for header fill and title bar.
        lang: Language code ("pt", "en", "es") for stats string localisation.
    """
    sheet_names = list(groups.keys())
    num_sheets = len(sheet_names)

    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">\n'
        '    <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n'
        '    <Default Extension="xml" ContentType="application/xml"/>\n'
        '    <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>\n'
        '    <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>\n'
    )
    for sheet_index in range(1, num_sheets + 1):
        content_types += f'    <Override PartName="/xl/worksheets/sheet{sheet_index}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>\n'
    content_types += "</Types>"

    rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n'
        '    <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>\n'
        "</Relationships>"
    )

    workbook = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"'
        ' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">\n'
        "    <sheets>\n"
    )
    for sheet_index, sheet_name in enumerate(sheet_names, 1):
        safe_name = escape_xml(sheet_name)[:31]
        workbook += f'        <sheet name="{safe_name}" sheetId="{sheet_index}" r:id="rId{sheet_index}"/>\n'
    workbook += "    </sheets>\n</workbook>"

    wb_rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n'
    )
    for sheet_index in range(1, num_sheets + 1):
        wb_rels += (
            f'    <Relationship Id="rId{sheet_index}"'
            ' Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet"'
            f' Target="worksheets/sheet{sheet_index}.xml"/>\n'
        )
    wb_rels += (
        '    <Relationship Id="rIdStyles"'
        ' Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles"'
        ' Target="styles.xml"/>\n'
        "</Relationships>"
    )

    with zipfile.ZipFile(dest_path, "w", zipfile.ZIP_DEFLATED) as xlsx_file:
        xlsx_file.writestr("[Content_Types].xml", content_types)
        xlsx_file.writestr("_rels/.rels", rels)
        xlsx_file.writestr("xl/workbook.xml", workbook)
        xlsx_file.writestr("xl/_rels/workbook.xml.rels", wb_rels)
        xlsx_file.writestr("xl/styles.xml", _build_styles_xml(color_hex))

        for sheet_index, sheet_name in enumerate(sheet_names, 1):
            worksheet_bytes = _build_worksheet_xml(
                headers, groups[sheet_name], base_name, apparatus_label, lang
            )
            xlsx_file.writestr(f"xl/worksheets/sheet{sheet_index}.xml", worksheet_bytes)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """Convert a MindTrace CSV file to a formatted .xlsx workbook."""
    if len(sys.argv) < 2:
        sys.exit(1)

    source_path = sys.argv[1]
    if not os.path.exists(source_path):
        sys.exit(1)

    base_name = os.path.splitext(os.path.basename(source_path))[0]
    out_path = os.path.splitext(source_path)[0] + ".xlsx"

    all_rows = read_csv_rows(source_path)
    if not all_rows:
        sys.exit(0)

    headers = all_rows[0]
    data_rows = all_rows[1:]
    lang = detect_language(headers)
    apparatus_label, apparatus_color = detect_apparatus(headers, lang)

    groups, _ = group_rows_by_column(data_rows, headers, ["Par de Objetos", "Object Pair"], lang)

    create_xlsx(out_path, base_name, apparatus_label, headers, groups, apparatus_color, lang)

    if out_path != source_path and os.path.exists(out_path):
        try:
            os.remove(source_path)
        except Exception:
            pass


if __name__ == "__main__":
    main()
